# base
FROM node:22-alpine AS base

WORKDIR /usr/src/app

RUN npm install -g pnpm
RUN npm install -g @nestjs/cli

COPY package*.json ./

RUN pnpm install

COPY . .

RUN pnpm build

CMD ["pnpm", "start:dev"]
