services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    env_file:
      - ./.env
    ports:
      - '3001:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
